<?php
/**
 * TL_ROOT/system/modules/be_email/languages/de/modules.php 
 * 
 * Contao extension: be_email 1.1.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Marko Cupic, 2010 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['tl_be_email']['0'] = "E-Mail";
$GLOBALS['TL_LANG']['MOD']['tl_be_email']['1'] = "Anderen Backend Benutzern eine E-Mail schreiben.";
 
?>
