<?php
/**
 * TL_ROOT/system/modules/be_email/languages/de/tl_be_email.php
 *
 * Contao extension: be_email 1.1.1 stable
 * Deutsch translation file
 *
 * Copyright : &copy; Marko Cupic, 2010
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Marko Cupic (markocupic)
 * Translator: Marko Cupic (markocupic)
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_be_email']['users']['0'] = "Benutzer Adressbuch";
$GLOBALS['TL_LANG']['tl_be_email']['members']['0'] = "Mitglieder Adressbuch";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsTo']['0'] = "To:";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsTo']['1'] = "Empfänger hinzufügen.";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsCc']['0'] = "CC:";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsCc']['1'] = "Carbon-Copy";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsBcc']['0'] = "BCC:";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsBcc']['1'] = "Blind-Carbon-Copy";
$GLOBALS['TL_LANG']['tl_be_email']['subject']['0'] = "Betreff";
$GLOBALS['TL_LANG']['tl_be_email']['subject']['1'] = "Betreff für die Nachricht";
$GLOBALS['TL_LANG']['tl_be_email']['content']['0'] = "Nachricht";
$GLOBALS['TL_LANG']['tl_be_email']['content']['1'] = "Inhalt der E-Mail";
$GLOBALS['TL_LANG']['tl_be_email']['attachment']['0'] = "Dateien aus dem Dateisystem auswählen";
$GLOBALS['TL_LANG']['tl_be_email']['attachment']['1'] = "Wählen Sie eine oder mehrere Dateien aus dem Dateisystem aus.";
$GLOBALS['TL_LANG']['tl_be_email']['removeAttachments']['0'] = "Ausgewählte Dateianhänge entfernen";
$GLOBALS['TL_LANG']['tl_be_email']['addAttachment']['0'] = "Dateianhäge hinzufügen";
$GLOBALS['TL_LANG']['tl_be_email']['fileupload']['0'] = "Dateiupload";
$GLOBALS['TL_LANG']['tl_be_email']['new']['0'] = "Neue E-Mail";
$GLOBALS['TL_LANG']['tl_be_email']['new']['1'] = "Eine neue E-Mail schreiben";
$GLOBALS['TL_LANG']['tl_be_email']['edit']['0'] = "E-Mail bearbeiten";
$GLOBALS['TL_LANG']['tl_be_email']['edit']['1'] = "E-Mail mit ID %s bearbeiten.";
$GLOBALS['TL_LANG']['tl_be_email']['delete']['0'] = "E-Mail löschen";
$GLOBALS['TL_LANG']['tl_be_email']['delete']['1'] = "E-Mail mit ID %s löschen.";
$GLOBALS['TL_LANG']['tl_be_email']['show']['0'] = "E-Mail anzeigen";
$GLOBALS['TL_LANG']['tl_be_email']['show']['1'] = "E-Mail mit ID %s anzeigen.";
$GLOBALS['TL_LANG']['tl_be_email']['emailNotSent'] = array('Entwurf');

// Legends
$GLOBALS['TL_LANG']['tl_be_email']['recipients_legend'] = "Empfänger";
$GLOBALS['TL_LANG']['tl_be_email']['message_legend'] = "Nachricht";
$GLOBALS['TL_LANG']['tl_be_email']['attachment_legend'] = 'Dateianhänge';
$GLOBALS['TL_LANG']['tl_be_email']['send_email'] = 'E-Mail senden';
$GLOBALS['TL_LANG']['tl_be_email']['address_book'] = 'Adressbuch';
$GLOBALS['TL_LANG']['tl_be_email']['add_recipients'] = 'Empfänger hinzufügen';

// Buttons
$GLOBALS['TL_LANG']['tl_be_email']['copyAndResendEmail'] = 'Email erneut versenden';
$GLOBALS['TL_LANG']['tl_be_email']['closeEditView'] = 'Zurück';

// Messages
$GLOBALS['TL_LANG']['tl_be_email']['confirmMessageHasBeenSent'] = 'Ihre Nachricht wurde versandt.';
$GLOBALS['TL_LANG']['tl_be_email']['entriesFound'] = 'Einträge gefunden';

// Placeholders
$GLOBALS['TL_LANG']['tl_be_email']['searchForName'] = 'Suche nach Name';
