<?php
/**
 * TL_ROOT/system/modules/be_email/languages/de/tl_settings.php 
 * 
 * Contao extension: be_email 1.1.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Marko Cupic, 2010 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['be_email_legend'] = "Backend E-Mail-Einstellungen";
$GLOBALS['TL_LANG']['tl_settings']['address_popup_settings']['0'] = "Adressbuch-Einstellungen";
$GLOBALS['TL_LANG']['tl_settings']['address_popup_settings_reference']['select_members_and_users'] = "Mitglieder- und Benutzer-Adressen anzeigen";
$GLOBALS['TL_LANG']['tl_settings']['address_popup_settings_reference']['select_users_only'] = "Nur Benutzer-Adressen anzeigen";
$GLOBALS['TL_LANG']['tl_settings']['address_popup_settings_reference']['select_members_only'] = "Nur Mitglieder-Adressen anzeigen";
 
