<?php
/**
 * TL_ROOT/system/modules/be_email/languages/de/tl_user.php 
 * 
 * Contao extension: be_email 1.1.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Marko Cupic, 2010 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['alternate_email']['0'] = "Zweite E-Mail-Adresse";
$GLOBALS['TL_LANG']['tl_user']['alternate_email']['1'] = "Bitte geben Sie eine gültige E-Mail-Adresse ein.";
$GLOBALS['TL_LANG']['tl_user']['alternate_email_2']['0'] = "Dritte E-Mail-Adresse";
$GLOBALS['TL_LANG']['tl_user']['alternate_email_2']['1'] = "Bitte geben Sie eine gültige E-Mail-Adresse ein.";
 
?>
