<?php
/**
 * TL_ROOT/system/modules/be_email/languages/fr/modules.php 
 * 
 * Contao extension: be_email 2.1.0 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; Marko Cupic, 2012 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Lionel Maccaud (lionel), http://lionelmaccaud.ch 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['tl_be_email']['0'] = "E-mail";
$GLOBALS['TL_LANG']['MOD']['tl_be_email']['1'] = "Écrire un e-mail aux autres utilisateurs du back office.";
 
?>
