<?php
/**
 * TL_ROOT/system/modules/be_email/languages/fr/tl_be_email.php 
 * 
 * Contao extension: be_email 2.1.0 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; Marko Cupic, 2012 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Lionel Maccaud (lionel), http://lionelmaccaud.ch 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_be_email']['users']['0'] = "Utilisateurs";
$GLOBALS['TL_LANG']['tl_be_email']['members']['0'] = "Membres";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsTo']['0'] = "À:";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsTo']['1'] = "Ajouter des destinataires.";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsCc']['0'] = "CC:";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsCc']['1'] = "Copie carbone";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsBcc']['0'] = "CCI:";
$GLOBALS['TL_LANG']['tl_be_email']['recipientsBcc']['1'] = "Copie carbone invisible";
$GLOBALS['TL_LANG']['tl_be_email']['subject']['0'] = "Sujet";
$GLOBALS['TL_LANG']['tl_be_email']['subject']['1'] = "Sujet de l'e-mail";
$GLOBALS['TL_LANG']['tl_be_email']['content']['0'] = "Message";
$GLOBALS['TL_LANG']['tl_be_email']['content']['1'] = "Contenu de l'e-mail";
$GLOBALS['TL_LANG']['tl_be_email']['removeAttachments']['0'] = "Supprimer les pièces jointes sélectionnées";
$GLOBALS['TL_LANG']['tl_be_email']['fileupload']['0'] = "Téléchargement de fichiers";
$GLOBALS['TL_LANG']['tl_be_email']['new']['0'] = "Nouvel e-mail";
$GLOBALS['TL_LANG']['tl_be_email']['new']['1'] = "Écrire un nouvel e-mail";
$GLOBALS['TL_LANG']['tl_be_email']['edit']['0'] = "Éditer un e-mail";
$GLOBALS['TL_LANG']['tl_be_email']['edit']['1'] = "Éditer l'e-mail ID %s.";
$GLOBALS['TL_LANG']['tl_be_email']['delete']['0'] = "Supprimer un e-mail";
$GLOBALS['TL_LANG']['tl_be_email']['delete']['1'] = "Supprimer l'e-mail ID %s.";
$GLOBALS['TL_LANG']['tl_be_email']['show']['0'] = "Voir un e-mail";
$GLOBALS['TL_LANG']['tl_be_email']['show']['1'] = "Voir l'e-mail ID %s.";
$GLOBALS['TL_LANG']['tl_be_email']['addAttachment']['0'] = "Ajoutez des pièces jointes";
$GLOBALS['TL_LANG']['tl_be_email']['attachment']['0'] = "Choisissez des fichiers";
$GLOBALS['TL_LANG']['tl_be_email']['attachment']['1'] = "Choisissez une ou plusieurs fichiers.";
$GLOBALS['TL_LANG']['tl_be_email']['recipients_legend'] = "Destinataires";
$GLOBALS['TL_LANG']['tl_be_email']['message_legend'] = "Messages";
$GLOBALS['TL_LANG']['tl_be_email']['attachment_legend'] = "Attachments";
$GLOBALS['TL_LANG']['tl_be_email']['send_email'] = 'Envoie e-mail';

