<?php
/**
 * TL_ROOT/system/modules/be_email/languages/fr/tl_settings.php 
 * 
 * Contao extension: be_email 2.1.0 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; Marko Cupic, 2012 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Lionel Maccaud (lionel), http://lionelmaccaud.ch 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['be_email_legend']['0'] = "Paramètres de l'extension be_mail";
$GLOBALS['TL_LANG']['tl_settings']['address_popup_settings']['0'] = "Paramètres du carnet d'adresses";
$GLOBALS['TL_LANG']['tl_settings']['address_popup_settings_reference']['select_members_and_users'] = "Afficher les adresses des membres et des utilisateurs";
$GLOBALS['TL_LANG']['tl_settings']['address_popup_settings_reference']['select_users_only'] = "Afficher les adresses des utilisateurs uniquement";
$GLOBALS['TL_LANG']['tl_settings']['address_popup_settings_reference']['select_members_only'] = "Afficher les adresses des membres uniquement";
 
?>
