<?php
/**
 * TL_ROOT/system/modules/be_email/languages/fr/tl_user.php 
 * 
 * Contao extension: be_email 2.1.0 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; Marko Cupic, 2012 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Lionel Maccaud (lionel), http://lionelmaccaud.ch 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['alternate_email']['0'] = "Deuxième adresse e-mail";
$GLOBALS['TL_LANG']['tl_user']['alternate_email']['1'] = "Veuillez, s'il vous plaît, entrer une adresse e-mail valide.";
$GLOBALS['TL_LANG']['tl_user']['alternate_email_2']['0'] = "Troisième adresse e-mail";
$GLOBALS['TL_LANG']['tl_user']['alternate_email_2']['1'] = "Veuillez, s'il vous plaît, entrer une adresse e-mail valide.";
 
?>
